Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :shell, :path => "./bootstrap.sh"
  config.vm.network :forwarded_port, host: 51664, guest: 51664
  config.vm.network :forwarded_port, host: 5671, guest: 5671
  config.vm.network :forwarded_port, host: 5672, guest: 5672
  config.vm.network :forwarded_port, host: 5432, guest: 5432
  config.vm.network :forwarded_port, host: 12345, guest: 12345
  config.vm.synced_folder "../../.", "/mig", :nfs => true
  config.vm.network "private_network", ip: "192.168.50.110"
  config.vm.provider :virtualbox do |p|
    p.customize ['modifyvm', :id, '--memory', '2048']
    p.customize ["modifyvm", :id, "--cpus", 2]
  end
end
