Vagrant.configure(2) do |config|

  config.vm.provision :shell, :path => "./bootstrap.sh"

  config.vm.define "test" do |test|
    test.vm.box="ubuntu/trusty64"
    config.vm.network "private_network", ip: "192.168.50.110"

    test.vm.network :forwarded_port, host: 51664, guest: 51664
    test.vm.network :forwarded_port, host: 5671, guest: 5671
    test.vm.network :forwarded_port, host: 5672, guest: 5672
    test.vm.network :forwarded_port, host: 5432, guest: 5432
    test.vm.network :forwarded_port, host: 12345, guest: 12345
  end

  config.vm.define "build" do |build|
    build.vm.box = "ubuntu/xenial64"
    build.vm.provision :shell, :path => "./bootstrap.sh", :args => "ubuntu"
    build.vm.network "private_network", ip: "192.168.50.111"
  end

  config.vm.synced_folder "../../.", "/mig", :nfs => true

  config.vm.provider :virtualbox do |p|
    p.customize ['modifyvm', :id, '--memory', '2048']
    p.customize ["modifyvm", :id, "--cpus", 2]
  end
end
